- hosts: localhost
  tasks:
    - name: Deleting resource group - kiragroup
      azure_rm_resourcegroup:
        name: kiragroup
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg